//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWorld.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_House
    {
        public System.Guid Id { get; set; }
        public string HouseCode { get; set; }
        public string HouseTitle { get; set; }
        public string Address { get; set; }
        public Nullable<int> Floor { get; set; }
        public Nullable<int> TotalFloor { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> YearPrice { get; set; }
        public string ImgUrls { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Decorate { get; set; }
        public Nullable<int> HouseType { get; set; }
        public Nullable<int> Property { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
    }
}
