//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWorld.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_Info
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public Nullable<int> Type { get; set; }
        public string Remark { get; set; }
        public string Contact { get; set; }
        public string Tel { get; set; }
    }
}
