//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWorld.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartWorldEntities : DbContext
    {
        public SmartWorldEntities()
            : base("name=SmartWorldEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<D_House> D_House { get; set; }
        public virtual DbSet<D_HouseAndEquipment> D_HouseAndEquipment { get; set; }
        public virtual DbSet<D_Info> D_Info { get; set; }
        public virtual DbSet<S_Equipment> S_Equipment { get; set; }
        public virtual DbSet<S_User> S_User { get; set; }
    }
}
